---
- hosts: vagrant
  
  vars:
    gem_bin_path: ~/.rvm/gems/$ruby/bin
    user: vagrant
  
  # sudo: yes
  
  tasks: 
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: Update all packages
      apt: upgrade=dist
      sudo: yes
 
    # curl required to download RVM     
    - name: Ensure curl is installed (used to download RVM)
      apt: pkg={{ item }} state=installed
      tags: [packages]
      sudo: yes
      with_items:
        - curl       

    # INSTALL RVM
    - name: install RVM
      shell: curl -L https://get.rvm.io | bash -s stable --ruby creates=/home/vagrant/.rvm
      sudo: no
    
    # INSTALL Ruby 1.9.3
    - name: install Ruby 1.9.3 (as default)
      shell: /home/vagrant/.rvm/bin/rvm install --default ruby-1.9.3-p484 creates=/usr/local/rvm/rubies/ruby-1.9.3-p484
      tags: [ruby]
      sudo: yes

    # Print a useful warning
    - name: NOTICE! You will need to exit the terminal and open a fresh terminal before you can use RVM. \n(Or alternatively run 'source /home/vagrant/.rvm/scripts/rvm
      shell: echo "You will need to exit the terminal and open a fresh terminal before you can use RVM. \n(Or alternatively run 'source /home/vagrant/.rvm/scripts/rvm'"
      sudo: no


