---
- hosts: vagrant
  
  vars:
    gem_bin_path: ~/.rvm/gems/$ruby/bin
    user: vagrant
  
  sudo: yes
  
  tasks: 
    - name: install jekyll
      gem: name=jekyll state=latest

    - name: install jekyll-pagination
      gem: name=jekyll-pagination

    - name: install python-pygments
      apt: pkg={{ item }} state=installed
      tags: [packages]
      with_items:
        - python-pygments    

    - name: install sass
      gem: name=sass state=latest
