---
- hosts: vagrant
  
  vars:
    gem_bin_path: ~/.rvm/gems/$ruby/bin
    user: vagrant
  
  sudo: yes
  
  tasks: 
    # Note that we run gem install commands via the Shell rather than directly in Ansible because that seems to be necessary to play nicely with RVM
    - name: install liquid (required by Jekyll)
      shell: gem install liquid -v 2.4.1

    - name: install kramdown (required by Jekyll)
      shell: gem install kramdown -v 0.13.8

    # Installing old version of Maruku as newer version fowls up Javascript by wrapping it in CDATA tag
    - name: install maruku (required by Jekyll)
      shell: gem install maruku -v 0.6.1
      
    - name: install jekyll
      # gem: name=jekyll version=0.12.1 state=present    NOTE: The Ansible gem module does not appear to be compatible with RVM
      shell: gem install jekyll -v 0.12.1 --no-ri --no-rdoc

    - name: set terminal encodings to be jekyll friendly (i.e. utf-8)
      shell: echo -e "export LC_ALL=en_US.UTF-8 \nexport LANG=en_US.UTF-8" >> /home/vagrant/.bashrc

    - name: install jekyll-pagination
      # gem: name=jekyll-pagination version=0.0.4 state=present    NOTE: The Ansible gem module does not appear to be compatible with RVM
      shell: gem install jekyll-pagination -v 0.0.4

    - name: install python-pygments
      apt: pkg={{ item }} state=installed
      tags: [packages]
      with_items:
        - python-pygments    

    - name: install sass
      # gem: name=sass version=3.2.5 state=present    NOTE: The Ansible gem module does not appear to be compatible with RVM
      shell: gem install sass -v 3.2.5
